### ISSUE TITLE
Recommend full URI to issues instead of just the number

### ISSUE THREAD

**Issue by underyx** [slashsBin/styleguide-git-commit-message#19]
We always copy paste the entire URL to the issue in the last line instead of just #123.

1. This makes it easy to open the issue when you're browsing the repo somewhere other than your issue tracker — I could just cmd-click on `Fixes https://github.com/slashsBin/styleguide-git-commit-message/issues/1` in the terminal while reading the git log.
2. It allows you to migrate to a new issue tracker (such as github to gitlab) without any confusion.

**Comment by underyx** [comment]
@slashsBin not interested in this change?

**Comment by slashsbin** [comment]
hi
I'm sorry for the delay, I was super busy with a new product launch.

Actually, I don't totally agree with you, although I agree that doing so will improve terminal log viewing.

Personally, for me, it's an overkill to paste the full URL because I need to copy/paste it from somewhere else beforehand.

Another thing is, doing so may break [automatcally closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/).

Maybe we should simplify browsing issues by other means like:
- PHPStorm: [Issue Navigation](https://www.jetbrains.com/help/phpstorm/2017.2/issue-navigation.html?utm_medium=help_link&utm_source=from_product&utm_campaign=PS&utm_content=2017.2)
- iTerm2: [Smart Selection](https://www.iterm2.com/smartselection.html) & [Triggers](https://www.iterm2.com/triggers.html)

What do you think?

**Comment by slashsbin** [comment]
It seems like GitLab is OK with [automatic closing of issues by full URL](https://docs.gitlab.com/ee/user/project/issues/automatic_issue_closing.html).

**Comment by underyx** [comment]
GitHub is also okay with automatic closing by full URL. I also found that I
almost never remember the issue number I'm working on so I need to
copy-paste it anyway. Especially when working with three-four digit issue
numbers.

**Comment by slashsbin** [comment]
hi
please check rule#4.
any suggestions?

**Comment by underyx** [comment]
Perfect, we can consider this issue closed, thank you!
